### ISSUE TITLE
niri.windows appears unsorted

### ISSUE THREAD

**Issue by erinsugar** [imiric/qml-niri#5]
I'm trying to display a Rectangle for each window open on the focused window's workspace.
The list niri.windows appears unsorted, so the Rectangles don't appear in any predictable order.
I'm new to this so please let me know if you'd like any more information.

```
RowLayout {
  anchors.verticalCenter: parent.verticalCenter
  spacing: 4

  Repeater {
    model: niriob.windows

    Rectangle {
      visible: model.workspaceId == niriob.focusedWindow?.workspaceId
      width: 12
      height: 12
      color: model.isFocused ? "#ffffffff" : "#ff777777"
      radius: 6
    }
  }
}
```

For example, I'd like the focused window to be highlighted on the second indicator on the bar.
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/8b047c25-dd9a-488b-8bcd-132e390edf1c" />

**Comment by imiric** [comment]
Hi there! :wave: Thanks for opening this issue.

You're right, the windows order was not predictable.

It should be fixed by 0742997, so they're now sorted by their ID.

Cheers!

**Comment by erinsugar** [comment]
Thanks so much!

**Comment by ilylily** [comment]
that doesn't actually fix the problem. sorting by id will still cause windows to be out of order in `niri.windows` compared to their real position in the scrolling layout, just like in the screenshot

i wrote a patch that used the windows' json `layout` object's `pos_in_scrolling_layout` array (encoded from a 2-tuple in niri's source)... but that also presented an issue. when window layout positions change, `WindowModel::handleWindowsChanged` is not always called - perhaps because the list itself (that is, the list of pointers internal to qt) isn't changing, only its members' contents. pure speculation, mind you

i think the right call here might be making the `windows` property in `niri.h` point to a [QSortFilterProxyModel](https://doc.qt.io/qt-6/qsortfilterproxymodel.html) which proxies the actual `WindowModel`, but i'm completely new to qml and c++ so i'm not sure. it might even simply be correct to sort the list of windows before returning it to qml every time 🤷

**Comment by imiric** [comment]
Thanks for the patch @ilylily, but IMO the original issue of the windows list being unsorted was addressed. Returning the list in the order they're shown on screen is a separate feature request, and TBH I'm not sure that it's something that should be done by the plugin.

Such a feature presents several challenges. E.g. how should floating windows be ordered? The plugin would need to keep track of x/y positions of all windows, which the current model doesn't expose, and then return the list of windows sorted by display -> workspace -> position in layout. The plugin would also need to handle the `WindowLayoutsChanged` event, which is currently ignored, and if it's not always called as you found out, then we'd need to figure out a workaround.

This is all additional complexity, which most users likely won't need. I personally don't, at least currently, though I would like to eventually expose window coordinates and size.

Besides, advanced sorting can always be done in QML. That C++ `QSortFilterProxyModel` class you found [is also accessible from QML](https://doc.qt.io/Qt-6/qml-qtqml-models-sortfilterproxymodel.html). This is arguably the better place for that anyway, since the order is not hardcoded and can be easily customized by the user.

Here's a patch to `test_windows.qml` that uses `SortFilterProxyModel`:
```patch
diff --git a/test/test_windows.qml b/test/test_windows.qml
index 3b50a1a..18eadc2 100644
--- a/test/test_windows.qml
+++ b/test/test_windows.qml
@@ -1,6 +1,7 @@
 import QtQuick
 import QtQuick.Controls
 import QtQuick.Layouts
+import QtQml.Models
 import Niri 0.1

 ApplicationWindow {
@@ -36,6 +37,17 @@ ApplicationWindow {
         }
     }

+    SortFilterProxyModel {
+        id: sortedWindows
+        model: niri.windows
+
+        sorters: [
+            // Sort by workspace, then by window ID.
+            RoleSorter { roleName: "workspaceId" },
+            RoleSorter { roleName: "id" }
+        ]
+    }
+
     ColumnLayout {
         anchors.fill: parent
         anchors.margins: 10
@@ -110,7 +122,7 @@ ApplicationWindow {
             Layout.fillWidth: true
             Layout.fillHeight: true

-            model: niri.windows
+            model: sortedWindows
             spacing: 5
             clip: true

```

I tested this to work with Quickshell v0.2.1, which is built with Qt 6.10.

If that doesn't work for you, then the list can always be sorted manually in JavaScript. Sure it would be slower than doing it in C++, but the window count will be small, so the performance overhead would be negligible.

So I'll have to reject your PR, but thanks for the interest and suggestion. ☺️ Merry Christmas! 🎄

**Comment by ilylily** [comment]
the original issue included a screenshot of the problem, which sorting by id doesn't fix. i think you're right, the user of the plugin should be able to sort windows themselves however they like. if qml-niri isn't the right place to sort the list, layout information should at least be exposed to the user so it can be sorted in qml as you said; currently this is simply impossible, hence this issue in the first place. handling `WindowLayoutsChanged` should be an easy fix, and it would solve the issue completely with practically no added complexity. i can submit a pr soon, depending on just how busy the holidays are for me 🙂

i also have a quick correction which should reduce the apparent complexity. i never said `WindowLayoutsChanged` is not always called when window layouts change. i said `WindowModel::handleWindowsChanged` (which is triggered by the niri event `WindowsChanged`) is not called when window properties change

wishing you and your family a very merry christmas 🙏

**Comment by imiric** [comment]
> the original issue included a screenshot of the problem, which sorting by id doesn't fix.

The issue title and description report the windows list being unsorted, causing the rendering to not be in a predictable order, which sorting by ID certainly solves. In any case, let's allow @erinsugar to determine if their issue was addressed or not.

What you're proposing is enhancing the sorting to include additional criteria, which I'm not opposed to, but like I said, this is better done in QML than in C++.

> layout information should at least be exposed to the user so it can be sorted in qml as you said

The windows list can be sorted in QML with the current version of the plugin, as showcased above. Exposing layout information would certainly provide more flexibility (not just for sorting), and enable the use case you're interested in.

So I'd be happy to review and accept a patch that simply exposes layout information. If you have the time and are willing to work on this, I'd appreciate it. :relaxed:

> i also have a quick correction which should reduce the apparent complexity. i never said `WindowLayoutsChanged` is not always called when window layouts change. i said `WindowModel::handleWindowsChanged` (which is triggered by the niri event `WindowsChanged`) is not called when window properties change

I see, I misread. If you think this is a bug in qml-niri, feel free to open a GH issue, and I'll look into it.

**Comment by erinsugar** [comment]
My intended use-case was to sort by position in layout. If this feature could be implemented, that would be fantastic.
I'm glad niri.windows is now sorted, so users can make use of that, so while adding a feature to sort by layout position would be perfect, I'm not too fussed one way or another.

**Comment by imiric** [comment]
Hey, just an update. Thanks to @bingo084 the plugin now exposes layout information, which makes it possible to sort windows by layout properties as well. I added an example in https://github.com/imiric/qml-niri/commit/c2f52db9c2dc1e189285c9067a6a79ccc2e22edc.

The example only showcases sorting tiled windows, but more complex sorting could be done based on floating window position as well, if needed.
